### ISSUE TITLE
Block light flickering

### ISSUE THREAD

**Issue by power2220** [gri573/rethinking-voxels#5] opened 2022-12-04 01:52 UTC
When I move, block lighting flickers

https://www.youtube.com/watch?v=3qDPg-QNy8Y

If there is a way to fix this, please let me know.

**Comment by gri573** [comment] 2022-12-19 21:57
I think flickering like that may be caused by resource packs or mods, a small amount (much less than showcased in the video) is normal

**Comment by NicoandLuis** [comment] 2022-12-27 19:30
Issue is still present even without any resource packs both on Iris and on Optifine. Tried it with a AMD RX 6700.

[Example](https://i.redd.it/zur5x5x2gb8a1.png)

**Comment by Nev-eee** [comment] 2022-12-29 07:53
> No issues when I turn off Advanced Light Propagation.
I am using an AMD RX 6700 XT and can confirm that turning off advanced light propagation fixes this, at least on Iris.

**Comment by gri573** [comment] 2023-01-02 15:15
> Issue is still present even without any resource packs both on Iris and on Optifine. Tried it with a AMD RX 6700. No issues when I turn off Advanced Light Propagation.
> 
> [Example](https://i.redd.it/zur5x5x2gb8a1.png)

This amount of flickering is normal, especially with so many light sources around. Turning off advanced light propagation fixes this because it doesn't need to keep track of light source positions.

**Comment by NicoandLuis** [comment] 2023-01-03 08:30
From what I understand this shader has a very limited use when enabling Advanced Light Propagation. As in purely for screenshots with well placed light sources?
Nevertheless it runs very smooth when disabled and is very pretty.

**Comment by gri573** [comment] 2023-01-03 10:49
I personally find it very playable with advanced light propagation. yes, there are glitches/hard edges, but I prefer this over having smudgy shadows like in most PT shaderpacks. The screenshot you showcased is also an extreme case, usual vanilla terrain has a substantially lower amount of scattered light sources, and it can handle large blobs of lights as they appear in the nether better.

**Comment by power2220** [comment] 2023-01-03 13:28
i turned off the advanced light propagation, and it fixed most flickering.

**Comment by gri573** [comment] 2023-01-10 17:25
it should be much better now than it used to be a while ago

**Comment by CalebAShepherd** [comment] 2023-01-12 20:47
> it should be much better now than it used to be a while ago

Definitely better. I still experience it but less frequently. Any updates as to when it might be solved?

**Comment by NicoandLuis** [comment] 2023-01-14 11:07
> it should be much better now than it used to be a while ago

It certainly is now. Even the scene in the screenshot above is now looking fine.

**Comment by gri573** [comment] 2023-01-14 20:23
Solving it completely is near impossible as far as I can tell

**Comment by CalebAShepherd** [comment] 2023-01-15 18:03
> Solving it completely is near impossible as far as I can tell

Yes, it is so much better now. Distant light still flickers a little bit when it’s about 7-8 blocks away but when you get close to it it seems to stop permanently. Maybe if you can adjust the render distance of the light that might work?

**Comment by Frontear** [comment] 2023-01-22 19:53
Adding on that flickering seems to happen on player names as well. Not sure if this is related specifically to the light propagation, but maybe something else to note

**Comment by gri573** [comment] 2023-01-29 20:48
flickering should be decreased some more with the latest version

**Comment by gri573** [comment] 2023-02-08 07:31
flickering is much worse with entity voxelisation apparently

**Comment by gri573** [comment] 2023-06-08 16:29
this is largely fixed in the rewrite

**Closed by gri573** 2023-06-08 16:29 UTC
Labels: bug
