### ISSUE TITLE
Flickering shadows.

### ISSUE THREAD

**Issue by sssHpion007** [gri573/rethinking-voxels#65] opened 2023-02-07 22:17 UTC
In some houses in the village, you can notice this bug. It occurs when there are 2 or more light sources nearby and shadows try to overlap each other. Is it possible to make it so that 1 light source can illuminate the shadow of another?
https://imgur.com/Kn2Od7Y
[rethinking-voxels_beta16a.zip.txt](https://github.com/gri573/rethinking-voxels/files/10679830/rethinking-voxels_beta16a.zip.txt)

**Comment by gri573** [comment] 2023-02-08 07:31
it is theoretically possible, but not within the current iris/optifine shader pipeline. It will be fixed after iris 1.6 comes out. you can make it better by disabling entity voxelisation in voxelisation settings, however, it should only happen in the first place if at least 4 light sources are nearby (including on opposite sides of walls etc).
this is a duplicate of #5 , so I'll close it.

**Closed by gri573** 2023-02-08 07:31 UTC
