### ISSUE TITLE
Weird circular shadow rendering bug

### ISSUE THREAD

**Issue by BLUEChester** [gri573/rethinking-voxels#73] opened 2023-02-14 10:21 UTC
Very weird, not sure if this is a bug or some setting I have enabled by accident.
![Uploading image.png…]()
![2023-02-14_20 44 33](https://user-images.githubusercontent.com/68225807/218707462-abf358b6-ff1d-4b09-8932-b1d794c2abd1.png)

**Comment by gri573** [comment] 2023-02-17 21:23
I can't reproduce it, and your shadows also look a little messed up in other ways... which (if any) settings did you change and what does it look like on default settings?

**Comment by TwinShards** [comment] 2023-03-01 21:11
> I can't reproduce it, and your shadows also look a little messed up in other ways... which (if any) settings did you change and what does it look like on default settings?

Can reproduce. Same effect, this effect appear at the same angle as the sun(sun behind you).
(My Shadow was/is not "messed up")

**Comment by TwinShards** [comment] 2023-03-02 00:50
It also happen with the moon but with video compression AND YT compression it's basically not visible in the video sorry lol.
Just skip to when i change to day time.

https://youtu.be/kdm8h6904Hk

**Comment by gri573** [comment] 2023-06-08 16:34
fixed in the latest alpha

**Closed by gri573** 2023-06-08 16:34 UTC
Labels: bug, cannot reproduce
