### ISSUE TITLE
Underwater looks strange

### ISSUE THREAD

**Issue by zndrmn** [gri573/rethinking-voxels#34] opened 2023-01-27 02:39 UTC
Underwater looks strange, I think it has something to do with how you did the cave light leek prevention

Reimagined
![2023-01-26_20 31 41](https://user-images.githubusercontent.com/77690119/214998237-ec57bd83-cdcc-47b0-b2e3-67301387d4d0.png)

RVX above `Y=51.5`
![2023-01-26_20 31 48](https://user-images.githubusercontent.com/77690119/214998547-a314a2ee-25f6-4268-a4c1-153712fe7e5f.png)

RVX below `Y=51.5`
![2023-01-26_20 31 52](https://user-images.githubusercontent.com/77690119/214998578-dcccdb29-9f2e-47e4-8eaa-31732b9394d0.png)

**Comment by gri573** [comment] 2023-01-30 19:50
I fixed the below 51.5 issue, and I can't reproduce the other one
![image](https://user-images.githubusercontent.com/66473137/215580651-974f4660-85bc-4879-90ec-ebd82d56eea3.png)

**Comment by zndrmn** [comment] 2023-02-07 01:58
I figured out whats causing the dull colors
changing the translucent light tint value effects the water fog and light shaft color.

value set to `1.0`
![2023-02-06_19 53 17](https://user-images.githubusercontent.com/77690119/217128233-a4de8de4-3b6b-4716-8fb6-54a8a55b518f.png)
value set to `0.1`
![2023-02-06_19 53 31](https://user-images.githubusercontent.com/77690119/217128386-e180b2c6-7bbc-4b75-95a2-05e534796b3a.png)

**Comment by zndrmn** [comment] 2023-02-07 02:00
Also lines tend to show up underwater when the value is under `1`

**Comment by gri573** [comment] 2023-02-07 08:15
thanks for narrowing it down, the lightshafts being weird is fixed in the latest commit. I didn't see any lines though, so maybe that's still there

**Comment by zndrmn** [comment] 2023-02-07 08:29
awesome, the lines also seem to have gotten fixed so this should probably be closed

![2023-02-07_02 27 18](https://user-images.githubusercontent.com/77690119/217191769-1f21f042-6a2e-4aee-8084-184c10ffaaeb.png)

**Comment by gri573** [comment] 2023-02-07 09:04
yes, they are

**Closed by gri573** 2023-02-07 09:04 UTC
Labels: bug
