### ISSUE TITLE
Blinding Lava.

### ISSUE THREAD

**Issue by noobypandaa** [gri573/rethinking-voxels#127] opened 2023-04-11 16:24 UTC
Everything else seems to be fine except the lava emitting a really strong light.

![Lava bug](https://user-images.githubusercontent.com/130488920/231227178-f2005f38-5b78-46e3-a8b5-3fd6348d209d.jpg)

**Comment by Nooooooah818** [comment] 2023-04-12 20:47
how did you get the lava to emit light, for me the lava doesn't even glow

**Comment by gri573** [comment] 2023-04-15 19:38
please reset your video settings, this is a duplicate of #108

**Closed by gri573** 2023-04-15 19:38 UTC
