### ISSUE TITLE
Lightning Bug

### ISSUE THREAD

**Issue by KingofCreed** [gri573/rethinking-voxels#111] opened 2023-03-21 17:24 UTC
when you mix torchlight and the light from redstone lamps, as you can see here, it bends around on the floor. and the walls are also so dark at the top. In addition, I had to determine the fire gives no light from itself (so fireplace away and aquarium there).

if what is grammatically incorrect, this is all just translated because I do not know English.

![2023-03-21_18 02 03](https://user-images.githubusercontent.com/128512992/226689507-4aee59af-68e5-40b2-8402-bfb7878ba6cc.png)

**Comment by Elaski6573** [comment] 2023-03-23 10:46
I noticed that problem, too.
It seems to be a problem when mixed with light of different brightness.
In my case, it happened when the light of the torch and the lava mixed.

![image](https://user-images.githubusercontent.com/114150904/227169774-f111f268-33f5-45d8-96fd-90d572fe4482.png)

![image](https://user-images.githubusercontent.com/114150904/227173974-e56859fe-8dd2-4174-bd82-2755fedde522.png)

![image](https://user-images.githubusercontent.com/114150904/227176224-6ae8af67-5a62-47ee-8d3d-9c2f24919975.png)

**Comment by gri573** [comment] 2023-03-25 13:04
this is partially intended (the top of the wall being dark is intended because the lights are inside the ceiling, so the light would have to bend around to get to the top of the wall. you can reduce it if you enable cuboid-aware light source size in voxelisation settings -> advanced light propagation settings)), other parts (e.g. the issue that lighting isn't smooth or occasionally stops working are a duplicate of #39 )

**Closed by gri573** 2023-03-25 13:04 UTC
