### ISSUE TITLE
Flickering while moving, removing or placing blocks in caves/tight spaces with more than 2 light sources

### ISSUE THREAD

**Issue by ramen-to-go** [gri573/rethinking-voxels#30] opened 2023-01-24 22:13 UTC
### Issue Report
Hey,
I've noticed an interesting bug, while trying to play on my smp with advanced light propagation on. On my smp I got multiple mods, resource packs and datapacks installed so to make sure no other mod caused the issue I tested it on a fresh Minecraft instance.

#### Issue: 
Shadows start flickering quite intensively, as soon as light from two or more source try to light the same area around corners, it looks as if the lighting is fighting over where it exactly comes from (source 1 or 2). When I stop moving it settles down until I start moving again or until I place/mine a block. 

On my smp it's everywhere since I tend to use _a lot_ of torches. Same with caves, as soon as I start placing a few torches the staggered pattern of the walls seems to be enough to trigger the flickering again, although it sometimes occurs with only one light source in the room if multiple are outside of the room.

#### Version Info:
`
Minecraft version: 1.19.3,
Fabric loader version: 0.14.13,
Shader version: beta13a,
`

#### Additional Mods (Fresh Instance)
`
Iris v1.5.1, 
Mod Menu v5.0.2, 
Sodium v0.4.8+build.22
`

#### Additional Info:
- Turning off the Occlusion Bleeding Fix reduces the flickering a little bit
- Basic Light Propagation not affected at all
- Performance of Shader otherwise great, little to no lag
- My Shader Config File: [rethinking-voxels_beta13a.zip.txt](https://github.com/gri573/rethinking-voxels/files/10494068/rethinking-voxels_beta13a.zip.txt)
- Video of the Issue: [https://youtu.be/-uB4basRKU4](https://youtu.be/-uB4basRKU4)

I hope this helps you :)
If you have any questions about my setup/configs, feel free to ask :)

**Comment by gri573** [comment] 2023-01-25 08:31
I had this issue reported to me by someone on discord, but I haven't been able to reproduce it. I'll check on other platforms once I coordinate it with the friends of mine who usually allow me to use their computers for testing

**Comment by gri573** [comment] 2023-01-25 08:48
this is technically a duplicate of #5 , but it is probably a different underlying issue, so I'll keep it open

**Comment by gri573** [comment] 2023-01-27 22:04
I could reproduce on a different computer and it is fixed in the latest commit

**Closed by gri573** 2023-01-27 22:04 UTC
Labels: bug
