### ISSUE TITLE
Shadow and flickering bug

### ISSUE THREAD

**Issue by hgdfhdrythtdryh** [gri573/rethinking-voxels#70] opened 2023-02-12 01:46 UTC
Whenever i move i can see huge shadows of animals even though they arent there. And i also see flickering.

Here is a example of it: https://gyazo.com/0ff510c0b4afbaa1d5bc50dd1d40839e
The quality isnt that bad as in the game but you get the point.

**Comment by hgdfhdrythtdryh** [comment] 2023-02-12 02:06
Btw forgot to say that a whole area just gets super bright like its follows me

**Comment by SteelChikorita** [comment] 2023-02-12 16:55
I have also had this issue with flickering distorted shadows whilst testing this shader with 1.19.2 Rubidium + Oculus (a Forge port of Iris)

**Comment by gri573** [comment] 2023-02-12 19:44
> Btw forgot to say that a whole area just gets super bright like its follows me

the brightness comes from GI with basic light propagation mode, you can disable GI for now and I'll fix it soon

**Comment by gri573** [comment] 2023-02-12 19:45
the animal shadows are a mod incompatibility, at least I think they are because people reporting them were always using several mods other than shader loaders

**Comment by ankalagon990** [comment] 2023-03-14 02:59
I am experiencing this as well. In a fresh forge pack with only oculus and rubidium installed (example: https://youtu.be/h0PcBYkxHVY ), in the normal MC Launcher with optifine; similar results (example: https://youtu.be/kNBoQF87MC8 ). 

In forge I get the same glitch with the shadows of mobs being rendered over everything, with optifine I get similar results but it doesn't look like it's just mob shadows that are affected. In both cases the shadows move in relation to the player. I've tried this with multiple versions (beta 17-18c) and always get the same or very similar results.

**Comment by gri573** [comment] 2023-03-14 19:29
please just upload videos directly to github (via drag and drop, for instance). I don't know what causes this and haven't been able to reproduce it so far, but it will probably be fixed soon-ish because I'm rewriting relevant parts of rethinking voxels (such as voxel mapping). At the same time, however, it will stop working on optifine and iris versions below 1.6. Oculus will potentially work once it updates to iris 1.6

**Comment by xameryn** [comment] 2023-04-02 21:03
Happens to me as well, the video shows mods present but after removing all but the listed mods the issues still occur. Is there a way to just disable entity shadows?

Using the following versions:
- Rubidium 0.5.5
- Oculus 1.5.2
- Rethinking Voxels 18c and 17b (occurs for both)

https://user-images.githubusercontent.com/11352382/229378662-dbbada42-42ee-445f-a4bb-2ca1eb77fa20.mp4


https://user-images.githubusercontent.com/11352382/229378664-bdb66dbb-b1b3-434c-ba49-ea793a703982.mp4

Will also post an issue on Oculus's page.

**Comment by gri573** [comment] 2023-06-08 16:34
this will be fixed once oculus updates to iris 1.6 or later and the rewrite starts working on it

**Closed by gri573** 2023-06-08 16:34 UTC
Labels: bug, mod support
