### ISSUE TITLE
Entire screen flickering including pause menu, main menu, and ingame

### ISSUE THREAD

**Issue by JackIt999** [gri573/rethinking-voxels#12] opened 2022-12-27 22:55 UTC
I have noticed that the entire screen flickers when using this shader only on both Iris and Opfifine. In game, it seems like the pause menu flickers in and out very quickly, though my game never pauses or stutters because of this, it is only a graphical issue. The same thing happens on the main menu, it just flickers rapidly but noticeably. It is not a subtle effect, it is quite intrusive. The flickering is not confined to certain things in game nor is it confined to any light sources. The entire screen flickers uniformly.

I apologize that I could not make a recording of the issue, because it is unclear what causes it to happen. Sometimes it is more subtle, other times it is downright unplayable.

**Comment by gri573** [comment] 2023-01-02 15:18
I am relatively certain that this is caused by some bad combination of this shader doing something, your graphics driver having bugs (every graphics driver has some) and potentially other mods interfering with the shader. I haven't encountered it, and it seems hard to reproduce, so I don't think I can fix it unless you can find a more precise cause

**Comment by gri573** [comment] 2023-01-15 10:17
I will close this now, and I will reopen it if you come back to me with more information

**Closed by gri573** 2023-01-15 10:17 UTC
