### ISSUE TITLE
ZOOM

### ISSUE THREAD

**Issue by eidosik** [gri573/rethinking-voxels#42] opened 2023-01-30 23:38 UTC
Hi, ZOOM function from OptiFine not working with Rethinking Voxels shader....

**Comment by gri573** [comment] 2023-01-31 10:36
That's very unlikely to be caused by the shader, did you try if it works with other shaders?

**Comment by jeffswt** [comment] 2023-02-01 13:49
Generally Zoom is implemented by changing the FoV, so if you're able to change the FoV but can't zoom, there's a 90% chance that the issue is not about the shader.

**Comment by gri573** [comment] 2023-02-02 09:20
I'll close this since it's probably not a shader bug

**Closed by gri573** 2023-02-02 09:20 UTC

**Comment by eidosik** [comment] 2023-02-02 11:49
other shaders work normally... only this shader. Others that I have support zooming only on overworld, nether or both ...

**Comment by gri573** [comment] 2023-02-02 19:24
You could use iris and logical zoom or some other zoom mod then

**Comment by eidosik** [comment] 2023-02-02 23:35
thanks, i try it... does the Iris also have a zoom function ?? like a OptiFine???

**Comment by kaxlabs** [comment] 2023-02-03 00:33
> thanks, i try it... does the Iris also have a zoom function ?? like a OptiFine???

No, but you can always grab the features from other mods like LogicalZoom.
