### ISSUE TITLE
Lava is blinding white

### ISSUE THREAD

**Issue by superdeadspace** [gri573/rethinking-voxels#122] opened 2023-04-09 23:52 UTC
![2023-04-09_19 51 49](https://user-images.githubusercontent.com/59935567/230802275-e9e30fe5-5569-4b5e-a1b6-c50b2f55f025.png)

**Comment by TRYTRY2222** [comment] 2023-04-10 01:12
at my pc lava is working fine also your water is looking diffrent are you sure you have the correct shader on?

**Comment by gri573** [comment] 2023-04-15 19:39
pleas reset your video settings, this is a duplicate of #108

**Closed by gri573** 2023-04-15 19:39 UTC
