### ISSUE TITLE
Terrible flickering and light-bleeding issues

### ISSUE THREAD

**Issue by Poly2it** [gri573/rethinking-voxels#24] opened 2023-01-14 18:36 UTC
Lighting flickers a lot and also bleeds through surfaces. The issues are more apparent when moving.  
Using Iris 1.5.0.  

![2023-01-14_19 34 27](https://user-images.githubusercontent.com/84731064/212490279-229f319e-9500-475d-ae3e-1ab4e68a839f.png)

**Comment by gri573** [comment] 2023-01-14 20:13
The flickering is a duplicate of #5 
If you mean the bright edges by light bleeding, turn on occlusion bleeding fix in voxelisation settings

**Closed by gri573** 2023-01-14 20:13 UTC
